name: Back-end Build Docker Compose
on:
  push:
    branches:
      - pre-prod
jobs:
  build-docker-compose:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Compose Services
        env:
          DOCKER_BUILDKIT: 1
        run: docker compose -p pgagi-website-pre-pod -f docker-compose-prepod.yml up --build -d

      - name: Cleanup (preserve build cache)
        run: |
          docker container prune -f
          docker image prune -f --filter "until=48h"
